INSERT INTO tb_categoria (titulo, cor) VALUES ('Educativos', '#00FFFF')
INSERT INTO tb_categoria (titulo, cor) VALUES ('VideoClipe', '#FFFFCC')
INSERT INTO tb_categoria (titulo, cor) VALUES ('engraçãdos', '#FFFFCC')

INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('REAGINDO a Portfólios Dos INSCRITOS','Nesse video vou reagir ao portfolio dos inscritos e trazer alguns insights que podem te ajudar no seu portfolio.','https://youtu.be/iQk2NveOTgQ?si=OT_xMaIgfGBpbTQB',1)
INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('REMOVER BLOATWARES do Windows', 'Como REMOVER os BLOATWARES do Windows em 2 cliques!!','https://youtu.be/D6h-aveKM7U?si=774Wt7aOIRm1SZ_V',2)
INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('Challenge 1: Decodificador de Texto - Programa ONE TURMA 5','Esse é o primeiro Challenge(desafio) do programa #ONE  da #Oracle  em parceria com a #Alura','https://youtu.be/iQk2NveOTgQ?si=OT_xMaIgfGBpbTQB',3)
INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('O que é ReactJS?','Neste vídeo, Vanessa Tonini e Mario Souto explicam isto para você falando sobre como esta ferramenta surgiu, para que ela serve, quais são suas aplicações e relação com outras ferramentas e como começar a trabalhar com ela.','https://www.youtube.com/watch?v=6IuQUgeDPg0',1)

 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'Quais as melhores práticas com React?', 'Recebemos o @Dev Soutinho nesse Hipsters Ponto Tube para falar sobre as melhores práticas com React e como você pode aproveitar melhor as possibilidades dessa tecnologia no cenário atual.', 'https://www.youtube.com/watch?v=k77WZrvuDQU',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('O que faz uma desenvolvedora front-end?', 'O que é Front-end? Trabalhando na área os termos HTML, CSS e JavaScript fazem parte da rotina das desenvolvedoras e desenvolvedores. Mas o que eles fazem, afinal? Descubra com a Vanessa!', 'https://www.youtube.com/watch?v=ZY3-MFxVdEw',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('O que é REST?', '', 'https://www.youtube.com/watch?v=weQ8ssA6iBU',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('NGINX: Servidor Web, Proxy Reverso e API Gateway', 'Gabs Ferreira conversou com o @Dias de Dev, que é instrutor aqui da Alura e criou nosso novo curso de NGINX', 'https://www.youtube.com/watch?v=I4oydqod7j0',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('Evolução do C++', 'O que mudou durante a evolução da linguagem C e quais são, de fato, as novidades do C++ moderno? Nosso instrutor, Vinicius Dias, explica nesse vídeo esse processo de evolução e que novidades surgiram.', 'https://www.youtube.com/watch?v=_n5hLYGjdfk',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('Java, Spring, Microserviços e vagas na Hotmart', 'Nessa live, Paulo Silveira conversa sobre a evolução do Java em microsserviços e sobre o caso da Hotmart com Marco Aurélio Ribeiro, especialista em desenvolvimento com 17 anos de carreira e trooper da Hotmart há mais de seis anos.', 'https://www.youtube.com/watch?v=f46tw7lOt_0',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('O que é Data Science?', 'Python é o novo Excel? Para que serve o R, Pandas e Jupyter? E qual é, afinal, a diferença entre o Data Science, Business Intelligence e Machine Learning? Descubra no primeiro episódio de Hipsters Ponto Tube!', 'https://www.youtube.com/watch?v=5b9Z8toVaAU',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('Aprenda tudo sobre Data Science, seus primeiros passos', 'Você é entusiasta de Inteligência artificial, é do mundo Python, de BI etc e quer aprender sobre Data Science? Preparamos este curso pra você!', 'https://www.youtube.com/watch?v=IQdISZCosAE',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ('Quais as profissões em Ciência de Dados? com Mikaeri Ohana', 'Quer saber qual carreira seguir na área de Ciência de Dados? A Mikaeri Ohana, especialista em Data Science, te ajuda a descobrir alguns caminhos para mergulhar nessa profissão.', 'https://www.youtube.com/watch?v=5CHLH9LU1Uc',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'Aprenda a transformar design em código com o Figma', 'A Rafaella Ballerini, instrutora de Front-End na Alura, vem trazer várias dicas pra você transformar o design em código. Aprenda como exportar imagens, ícones e inspecionar os elementos direto do Figma.', 'https://www.youtube.com/watch?v=sup2hlWm5yE',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'Qual é a diferença entre back-end e front-end?', 'Afinal, existe diferença entre back-end e front-end? Nesse Alura+, o nosso instrutor Vinícius Dias vai responder a essa questão tão recorrente no mundo do desenvolvimento.', 'https://www.youtube.com/watch?v=a-l4z6V2yXA',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'Introdução ao Postman', 'As APIs são muito utilizadas para integrações de sistemas diversos. Mas, como fazer testes com elas sem utilizar um navegador e verificar seu retorno? O Vinicius Dias explica neste vídeo utilizando a ferramenta Postman.', 'https://www.youtube.com/watch?v=op81bMbgZXs',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'O que é ORM?', 'Afinal, o que é, como funciona e para que serve um ORM? O instrutor Guilherme Lima explica neste Alura+ com exemplos práticos e simplificados.', 'https://www.youtube.com/watch?v=x39vqeBTUmE',1)
 INSERT INTO tb_video (titulo, descricao, url, categoria_id) VALUES ( 'O que é Deep Learning?', 'Afinal, o que é Deep Learning e onde se aplica? O Gui Silveira explica neste vídeo além de outros conceitos que rodeiam este tema como as redes neurais densas, estimadores, classificadores e mais.', 'https://www.youtube.com/watch?v=kryIBKPVZ7A,1'


INSERT INTO tb_role (authority) VALUES ('ADMIN')
INSERT INTO tb_role (authority) VALUES ('USER')

INSERT INTO tb_user (name, email, password) VALUES ('André', 'andre@gmail.com',1234)
INSERT INTO tb_user (name, email, password) VALUES ('Maria Edneia', 'maria@gmail.com',1234)
INSERT INTO tb_user (name, email, password) VALUES ('Davi', 'davi@gmail.com',1234)
INSERT INTO tb_user_role (user_id, role_id) VALUES (1,1)
INSERT INTO tb_user_role (user_id, role_id) VALUES (2,2)
INSERT INTO tb_user_role (user_id, role_id) VALUES (3,1)
INSERT INTO tb_user_role (user_id, role_id) VALUES (3,2)